language: node_js
cache:
    npm: false
node_js:
- lts/*
before_script:
- npm install -g grunt-cli npm
env:
  global:
    secure: Mcnk2Q/XmDOEtGMFepDXlSIJ+bjUJdPNahduWUqjoKUjyj5ujjG90MX+iF8qk+6VzrJ/d+0mPGS2rx+g+oT5/4Vbg0MYclSvxQ+idK6cmCAFEGzj8u/0vNsDQpf9ncIecesuriXTi9L2yd17rSaX3iNERoYW8o86RVXwksk3nPZql/AIB692qjjpS0mopQdPJl9rc0EtSRsc/lj/FQ5+zlJqyK/3Hi+OtvbL3DCu6yE6NXZ2PCgbCSidauqjfwh3+q/548dsxgRsmDjaLXru17FUAR3/YgL/Q9nrkA3G0iv9D+mOdkD7WMYBusm7m1ocazssfcYbs64XAAz2JOZ3HeN+4TN27NGP59I9mtCq5UHP1JI27QviQXRqrmo4StBeimUnypuKy7IUJGF8VBzfe2aWZa+1/FQBli52yUVrKwYJwVLdSePzjDhgOlAtS63XzrXLmw3rGS1XrQytbRUG84BZACHvR1DYXmB9PWoqKeHzNPEceXOw1cqAjDaegA69Fx/B9POh1V2w/B1SPsvWMJq3EQjdfb6wpy824yJyUCJINMcW+O5F5yL/JpaG2dMLiJsBw6/lHko+Fsdo0j4YWsGpV25EXXyUewpAf8FOXtieMtVWV5MxCA3q11o/apEWqs9OHlRh9KukFJsiFMxeOUhb6B5gOXJeNTN7iBGrawg=
