language: node_js
node_js:
- node
before_script:
- npm install -g grunt-cli npm
env:
  global:
    secure: nQ+9rvyH3nQUkQamk55JSiqv1Id1BPhiLASyZVxMM0oB1FzWbzVZEFesEKjP3Z11xBTKBQk5g4b3EPJU4uWg+A2O6bXMbScdLGyXP2idSDrsXY5OISJlJkJTYg3P1Lhr1g6+tKtWAt2KpU0cmJnw44fgyQjEgR0SDiVsgVgOtm7cWs6+3FZuWdyEAVOai9gkWCIghjU20oXVXAeBOg1p1Nsjiz8Ro+laPLHb2wx7bYZgSxXnCVHgQq4R9iAu9OPpLimyO1AU2FSKQXwZxmoVxv4N92fwr8LJNqHDbUNdSPwcdlxm8ktU5pS7ddPuyJq/nPupDRESifikUZda06UCznomXMEAryvfFP/lEcouTpZSiQ5mFbcmLstoJfN1Qgz0HQ1IJVtzZ8ps+hUIV3isgTQ7gNBdFX3SwsWgIH5Rl3gHIEFCJNZVQfuFWOb8iSW6f96b45Sxy5pG0UwIgWZJAqnGuHLfAqGhmCmG25D8SRlxuv5sN5htwTU95jczDMgZRPrY1BoGGjpzIQJqP32lv02GVrb06/UQkKVl/CvfXglb37PQX+xBqFuViiPM4qkGZguh4M5HX7jEMl5R+7l8n8PrV9NoI9KpzlxS75YUrB8pcSBDkptGW1DOWfjBdofwT6BPvCKwzB8MtwBYfCYy6VNjO9Km/Nk/cF/zn8tSLaM=
